spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/forum_server?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=CTT
    driver-class-name: com.mysql.cj.jdbc.Driver
#邮件设置
  mail:
    host: smtp.163.com
    username: lungzeongin@163.com
    password: BQLOHLFXQMDHBPCY
    properties:
      mail.smtp.port: 465
      mail.smtp.socketFactory.fallback: false
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.port: 465
  #文件大小设置
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
      file-size-threshold: 20MB


#redis-server.exe redis.windows.conf
  redis:
    database: 11
    host: 127.0.0.1
    port: 6379
#    password: kenRedis_123

#    nohup java -jar forum_server-0.0.1-SNAPSHOT.jar > consoleMsg.log 2>&1 &

#  # kafka启动命令(windows环境下)  bin\windows\zookeeper-server-start.bat   config\zookeeper.properties
###               bin\windows\kafka-server-start.bat config\server.properties
##  kafka:
##    listener:
##      missing-topics-fatal: false
##    bootstrap-servers: localhost:9092
###    bootstrap-servers: 47.115.88.155:9092
#    consumer:
#      group-id: forum-consumer-group
#      enable-auto-commit: true
#      auto-commit-interval: 3000

  data:
    elasticsearch:
      cluster-name: ken_forum
      cluster-nodes: 127.0.0.1:9300
#      cluster-nodes: 47.115.88.155:9300

  quartz:
    job-store-type: jdbc
    scheduler-name: forumScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5


server:
  port: 8089
  servlet:
    context-path: /forum_server

mybatis:
  mapper-locations: classpath:mapper/*.xml # 配置 Mapper XML 地址
  type-aliases-package: com.ken.forum_server.pojo # 配置数据库实体别名
  configuration:
    mapUnderscoreToCamelCase: true

#缓存配置
caffeine:
  posts:
    max-size: 15
    expire-seconds: 180


qiniu:
  key:
    access: V2agQcXe-v0jhGksaLTj36D2jpjnqYSKUf1rPyWB
    secret: QT-BZC2Xx9w-R3rFE9n9rHJAu1nJ615sBttJx8_F
  bucket:
    avatar:
      name: ken-forum-avatar
      url: qkllefrb5.hn-bkt.clouddn.com





