spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/forum_server?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=CTT
    driver-class-name: com.mysql.cj.jdbc.Driver
#邮件设置
  mail:
    host: smtp.163.com
    username: lungzeongin@163.com
    password: BQLOHLFXQMDHBPCY
    properties:
      mail.smtp.port: 465
      mail.smtp.socketFactory.fallback: false
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.port: 465
  #文件大小设置
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
      file-size-threshold: 20MB


#         redis-server.exe redis.windows.conf
  redis:
    database: 11
    host: 127.0.0.1
    port: 6379



  data:
    elasticsearch:
      cluster-name: ken_forum
      cluster-nodes: 127.0.0.1:9300
#      cluster-nodes: 47.115.88.155:9300

# 如果因为quartz而导致项目启动失败，那么就先清空qrtz相关表的数据，再启动
# 如果清空表的数据还是启动失败，那就注释掉下面的quartz的配置，这样quartz就会读取配置类的代码而不会去数据库读取配置
  quartz:
    job-store-type: jdbc
    scheduler-name: forumScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5


server:
  port: 8089
  servlet:
    context-path: /forum_server

mybatis:
  mapper-locations: classpath:mapper/*.xml # 配置 Mapper XML 地址
  type-aliases-package: com.ken.forum_server.pojo # 配置数据库实体别名
  configuration:
    mapUnderscoreToCamelCase: true

#缓存配置
caffeine:
  posts:
    max-size: 15
    expire-seconds: 180


# 七牛云的配置
qiniu:
  key:
    access: 
    secret: 
  bucket:
    avatar:
      name: 
      url: 
    picture:
      name: 
      url: 

root:
  fileUrl: "user.dir"

